services:
  postgres:
    image: postgres:17
    container_name: los_postgres
    restart: unless-stopped
    ports:
      - '5432:5432' # Map container port 5432 to local port 5432
    environment:
      POSTGRES_USER: los_user
      POSTGRES_PASSWORD: bluepineapple-los
      POSTGRES_DB: los_db

    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent data volume

  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: los_cloudbeaver
    restart: unless-stopped
    ports:
      - '8200:8978'
    depends_on:
      - postgres
    volumes:
      - cloudbeaver-data:/var/lib/cloudbeaver
# pass - bluepineapple-LOS9
volumes:
  pgdata: # This keeps data across container restarts
  cloudbeaver-data:
