name: PR Title Check

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ ^\[RELEASE\]\[(PATCH|MINOR|MAJOR)\]\[.*\]$ ]]; then
            echo "PR title is correctly formatted."
          else
            echo "Error: PR title must be in the format [RELEASE][PATCH|MINOR|MAJOR][Description]"
            exit 1
          fi
